import type {Metadata} from "next";
import {Geologica} from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";
import {Header} from "@/components/Header";

const geistMono = Geologica({
    variable: "--font-geologica",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistMono.variable} fs1`}>
                <Header/>
                {children}
            </body>
        </html>
    );
}
